# CI/CD Pipeline
# Author: pmayer.devopseng@gmail.com
# Build, Deploy, Display Ex. IP
# Format: see https://aka.ms/yaml

trigger:
- none  # switch to main for submission

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  displayName: 'Build'
  inputs:
    containerRegistry: 'DevOpsEng-DockerHub'
    repository: 'paulmayer2731 / web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  displayName: 'Deploy'
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Paul Mayer DevOps(3542213f-7e7a-4dad-aea4-fe30482ed0f3)'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    namespace: 'default'
    manifests: 'application-manifest.yaml'

- task: Kubernetes@1
  displayName: 'Kubernetes Login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'terraform-aks-cluster-sp'
    command:  login
- script: |
    kubectl describe services flask-app-service | grep 'LoadBalancer Ingress'
  displayName: LoadBalancer Ingress IP