# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none  # switch to main for submission

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DevOpsEng-DockerHub'
    repository: 'paulmayer2731 / web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Paul Mayer DevOps(3542213f-7e7a-4dad-aea4-fe30482ed0f3)'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    namespace: 'default'
    manifests: 'application-manifest.yaml'
    
- task: CmdLine@2
  inputs:
    script: |
      echo curl -s http://ipinfo.io/json | jq '.ip'
      
      echo Hello world

# - script: |
#     echo Image deployed to AKS.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
